# Builds on all branches & PRs
# Deploys to PyPi on "release".
name: Build, test and publish

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: pylint skytemple_files --load-plugins=pylint_deprecated_checker --rcfile=pylintrc
      env:
        PYTHONPATH: .